export default {
    // NOTE
    RESET_NOTES: 'RESET_NOTES',
    // // ADD NOTE
    ADD_NOTE_START: 'ADD_NOTE_START',
    ADD_NOTE_FAIL: 'ADD_NOTE_FAIL',
    ADD_NOTE_SUCCESS: 'ADD_NOTE_SUCCESS',

    // // ADD TAG
    ADD_TAG_START: 'ADD_TAG_START',
    ADD_TAG_FAIL: 'ADD_TAG_FAIL',
    ADD_TAG_SUCCESS: 'ADD_TAG_SUCCESS',

    REMOVE_TAG_START: 'REMOVE_TAG_START',
    REMOVE_TAG_FAIL: 'REMOVE_TAG_FAIL',
    REMOVE_TAG_SUCCESS: 'REMOVE_TAG_SUCCESS',

    REMOVE_NOTE_START: 'REMOVE_NOTE_START',
    REMOVE_NOTE_FAIL: 'REMOVE_NOTE_FAIL',
    REMOVE_NOTE_SUCCESS: 'REMOVE_NOTE_SUCCESS',
    // // CURRENT NOTE
    UPDATE_CURRENT_NOTE: 'UPDATE_CURRENT_NOTE',
    SET_CURRENT_NOTE: 'SET_CURRENT_NOTE',
    // // // SAVE CURRENT NOTE
    SAVE_NOTE_SUCCESS: 'SAVE_NOTE_SUCCESS',
    SAVE_NOTE_FAIL: 'SAVE_NOTE_FAIL',
    SAVE_NOTE_START: 'SAVE_NOTE_START',
    NOTE_UPDATE_STATUS: 'NOTE_UPDATE_STATUS',

    // // GET NOTES
    GET_NOTES_START: 'GET_NOTES_START',
    GET_NOTES_SUCCESS: 'GET_NOTES_SUCCESS',
    GET_NOTES_FAIL: 'GET_NOTES_FAIL',

    GET_NOTE: 'GET_NOTE',

    // AUTH
    CHECK_TOKEN_LOCAL_STORAGE: 'CHECK_TOKEN_LOCAL_STORAGE',
    // // LOGIN
    LOGIN_USER_START: 'LOGIN_USER_START',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
    // // LOGOUT
    LOGOUT_USER: 'LOGOUT_USER',
    // // SIGN UP
    SIGNUP_USER_START: 'SIGNUP_USER_START',
    SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
    SIGNUP_USER_FAIL: 'SIGNUP_USER_FAIL',
}