export default {
    // NOTE
    ADD_NOTE: 'ADD_NOTE',
    REMOVE_NOTE: 'REMOVE_NOTE',
    // // CURRENT NOTE
    UPDATE_CURRENT_NOTE: 'UPDATE_CURRENT_NOTE',
    SET_CURRENT_NOTE: 'SET_CURRENT_NOTE',

    // // GET NOTES
    GET_NOTES_START: 'GET_NOTES_START',
    GET_NOTES_SUCCESS: 'GET_NOTES_SUCCESS',
    GET_NOTES_FAIL: 'GET_NOTES_FAIL',

    GET_NOTE: 'GET_NOTE',

    // AUTH
    // // LOGIN
    LOGIN_USER_START: 'LOGIN_USER_START',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
    // // LOGOUT
    LOGOUT_USER: 'LOGOUT_USER',
    // // SIGN UP
    SIGNUP_USER_START: 'SIGNUP_USER_START',
    SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
    SIGNUP_USER_FAIL: 'SIGNUP_USER_FAIL',
}